name: Docker Build & Deploy Lambda using Terraform

on:
  push:
    branches:
      - main    # Trigger on push to the main branch
      - dev     # Trigger on push to the dev branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "ap-southeast-2"  # Updated AWS region to ap-southeast-2

    - name: Print success message after AWS credentials configuration
      run: echo "AWS credentials configured successfully!"

    - name: List S3 buckets to verify AWS connection
      run: |
        aws s3 ls
        echo "AWS S3 buckets listed successfully!"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        cd ai-fx
        docker build -t ai-fx .

    - name: Tag Docker image
      run: |
        docker tag ai-fx:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/ai-fx:latest

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-2.amazonaws.com/ai:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init terraform/

    - name: Apply Terraform to deploy Lambda
      run: terraform apply -auto-approve terraform/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Verify Lambda Deployment
      run: |
        aws lambda get-function --function-name my-lambda-function
